name: CI

permissions:
  contents: write

on:
    push:
        branches:
            - main
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "22.x"
            - run: node -v
            - name: Install pnpm
              run: npm install -g pnpm
            - run: npm install
            - run: npm run build
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4.3.3
              with:
                  branch: gh-pages # 部署后提交到那个分支
                  folder: dist # 这里填打包好的目录名称
